### ISSUE TITLE
Tip: Do not use `--network host`

### ISSUE THREAD

**Issue by Mastergalen** [qoomon/docker-host#13]
Just wanted to document this in case anyone else makes the silly mistake of running this container within network mode `host`.

This meant that all the iptables commands are run on the host, breaking anything network related such as SSH.

Even after stopping the docker container, the iptables changes persist.

Luckily I was able to revert the changes after following this answer on Serverfault:
https://serverfault.com/a/633623/155147

After resetting the iptables, you will also need to restart Docker itself.

**Comment by qoomon** [comment]
thanks for your tip
