### ISSUE TITLE
Container always stops

### ISSUE THREAD

**Issue by FractalMind** [qoomon/docker-host#15]
The docker-host container always stops after a few hours/days and don't restart automatically.

Notting relevant in the logs:
`Docker Host: 172.18.0.1 (default gateway),`

**Comment by qoomon** [comment]
thx for reporting, I will investigate

**Comment by qoomon** [comment]
Currently I have no clue why this is. I'm not able to reproduce it. 
Do you know the exit status of the container?
As workaround you may can add '--restart on-failure' to your docker run command.(I also added this parameter to README.md)

**Comment by qoomon** [comment]
please try the latest version of docker-host `qoomon/docker-host:2.0.4`

**Comment by qoomon** [comment]
I changed the keep alive strategy to `tail -f`
