### ISSUE TITLE
Call service on host machine from container

### ISSUE THREAD

**Issue by alexmacavei** [qoomon/docker-host#2]
Hey,

I'm trying to use your image to access a local service running on port 8080 from a running container. My setup is windows 8 with Docker Toolbox, so unfortuantely I have to go through virtualbox. I'm starting the container like so:
``` 
docker run -d --name dockerhost  --cap-add=NET_ADMIN --cap-add=NET_RAW qoomon/docker-host
```
Then I'm trying 
```
ping dockerhost
```
but it's not working. I'm assuming that's because it's not exposing any ports, but I would've expected the ping to be routed to my local Windows 8 OS. The ip returned that's being returned inside the docker-host container is the ip of the docker0 interface on the VM.
I must be missing something, maybe you can help out. 

Thanks

**Comment by qoomon** [comment]
are both container in the same docker network? if not so the dns resolving will not work.
easiest way is to use docker compose to do that.

**Comment by alexmacavei** [comment]
I guess they are if I'm not doing anything special. They should be in bridge network by default. I've got things working by running the container with the --add-host flag. It's still kinda weird that dockerhost returns the ip of the VirtualBox machine and not of my local host OS.
