### ISSUE TITLE
Docker toolbox - iptables: No chain/target/match by that name.

### ISSUE THREAD

**Issue by JamesWhitlock** [qoomon/docker-host#23]
I'm trying to run this on Docker Toolbox v18.09.3 on Windows but am unable to get the image to boot successfully. I've struggling to debug this, would you be able to advise how I might debug this further?

I start the container:
> $ docker run --name 'dockerhost'  --cap-add=NET_ADMIN --cap-add=NET_RAW --restart on-failure -d qoomon/docker-host

And docker ps reports the container is constantly restarting. Docker logs reports:
> $ docker logs dockerhost
> Docker Host: 172.17.0.1 (default gateway)
> iptables: No chain/target/match by that name.
> Docker Host: 172.17.0.1 (default gateway)
> iptables: No chain/target/match by that name.
> ...

> $ docker -v
> Docker version 18.09.3, build 774a1f4eee

Disabling the entrypoint and attaching, I found the first call to iptables fails
> iptables --table nat --insert PREROUTING --protocol tcp --match multiport --dports 0:65535 --jump DNAT --to-destination 172.17.0.1

Appears tables are empty:
> / # iptables -L -v
> Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination
> 
> Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination
> 
> Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination
>

**Comment by qoomon** [comment]
Unfortunately I have no access to a Windows computer however I found this https://docs.docker.com/docker-for-windows/networking/ you may can play around with some settings.

**Comment by qoomon** [comment]
Can you resolve host.docker.internal from within docker container?

**Comment by JamesWhitlock** [comment]
The issue is occuring within a virtualised boot2docker inside VirtualBox so should not be aware of the fact it is running on a windows host.

host.docker.internal does not resolve but it appears to find the gateway correctly 172.17.0.1

I'm not very au fait with iptables but it appears the problem is iptables can't find 'multiport'.

**Comment by qoomon** [comment]
Which virtual box base image do you use?

**Comment by bengtbrodersen0042** [comment]
May you can post the output of `cat /proc/net/ip_tables_matches` ?

**Comment by qoomon** [comment]
May you can post the output of cat /proc/net/ip_tables_matches ?

**Comment by JamesWhitlock** [comment]
Docker toolbox uses boot2docker under the hood which is supplied with docker toolbox. Version my version is shipped with is https://github.com/boot2docker/boot2docker/releases/download/v18.09.3/boot2docker.iso

>  # cat /proc/net/ip_tables_matches
> addrtype
> conntrack
> conntrack
> conntrack
> state
> addrtype
> icmp
> policy
> udplite
> udp
> tcp

**Comment by qoomon** [comment]
Well as you already figured out, it's because of the missing multiport module. 

Maybe I can install it? or implement a fallback for single nat rules.

**Comment by qoomon** [comment]
I think I found a way. WDYT
```shell
for forwarding_port in $(echo "$PORTS" | tr ";" " ")
do
  iptables --table nat --insert PREROUTING --protocol tcp \
    --dport "$forwarding_port" --jump DNAT --to-destination $DOCKER_HOST
  iptables --table nat --insert PREROUTING --protocol udp \
    --dport "$forwarding_port" --jump DNAT --to-destination $DOCKER_HOST
done
```

**Comment by qoomon** [comment]
just release version 2.3.0

**Comment by JamesWhitlock** [comment]
Great, it seems to be working. Thank you.

**Comment by qoomon** [comment]
Glad to hear that.
