### ISSUE TITLE
pass docker socket and auto determine host ip

### ISSUE THREAD

**Issue by hasnat** [qoomon/docker-host#28]
Can we have an option if user provides a docker socket, auto determine (if needed) the host ip within container.
removing the need for ~manually~ following on host
`docker network inspect bridge --format='{{( index .IPAM.Config 0).Gateway}}'`

**Comment by qoomon** [comment]
yes that would be possible
however you need to call `docker network inspect bridge --format='{{( index .IPAM.Config 0).Gateway}}'` manually?

**Comment by hasnat** [comment]
I meant if docker socket volumed calling
`docker network inspect bridge --format='{{( index .IPAM.Config 0).Gateway}}'`
within container

**Comment by qoomon** [comment]
@hasnat but why do you need to call `docker network inspect bridge --format='{{( index .IPAM.Config 0).Gateway}}'` at all? 
The docker-host container already determine the host ip automatically, doesn't it?

Can you give me a full example?

**Comment by qoomon** [comment]
docker-host container currently tries to determine host ip in the following order
* try to read environment variable `DOCKER_HOST`
* try to resolve `host.docker.internal` (`getent ahostsv4 host.docker.internal`)
* defaults to default gateway (`ip -4 route show default`)

**Comment by hasnat** [comment]
yes apologies for not reading the README correctly. I see in entrypoint what you just mentioned.

agreed with socket security risk.

Thanks for explaining, closing this one.

**Comment by qoomon** [comment]
You're welcome.
