### ISSUE TITLE
Setup Home Assistant on Mac using Docker-Host

### ISSUE THREAD

**Issue by aptonline** [qoomon/docker-host#30]
I’m trying to get my head around the setup of Docker-Host but struggling. I’m attempting to get home assistant running locally on my Mac  via docker but as per the instructions —net:host doesn’t seem to work on macOS: https://www.home-assistant.io/docs/installation/docker/

Any support setting docker-host up for Home-Assistant would be great.

**Comment by qoomon** [comment]
Maybe I don't get your situation right, but I think you don't need docker-host container at all.
just add `-p 8123:8123` to you docker run command like this `docker run --init -d --name="home-assistant" -e "TZ=America/Los_Angeles" -v /PATH_TO_YOUR_CONFIG:/config -p 8123:8123 homeassistant/home-assistant:stable`, then you should be able to access `http://localhost:8123` in your browser.

**Comment by aptonline** [comment]
Yes that’s works perfectly fine and I can set it up using that method but a lot of the integrations require `—net: host` enabled to be able to be detected on the same network and as you know that doesn’t seem to work in the same way on a Mac hence why I looked into a solution and found docker-host which if I’m not wrong allows all traffic to be routed to the containers.

**Comment by aptonline** [comment]
An example of this is the PlayStation 4 integration:  https://www.home-assistant.io/integrations/ps4/

**Comment by qoomon** [comment]
Actually its the other way around it allows to access docker host ports from within a docker container

**Comment by qoomon** [comment]
may this helps https://qiita.com/kjtanaka/items/f16757c1f0cc86ff225b

**Comment by snorkrat** [comment]
Sorry to post in a closed issue, but didn't feel this warranted a new one.  I too am wanting to access all container traffic **from** the macOS host for Home Assistant.  I understand this works the opposite way round, it allows the container to access the host ports/traffic.  Is there any way this can be modified to work the other way round?

**Comment by qoomon** [comment]
I don't think that's possible. You need to bind all container ports you need.
