### ISSUE TITLE
Is it possible to use with Docker Swarm ?

### ISSUE THREAD

**Issue by xirius** [qoomon/docker-host#31]
I have a docker swarm composed of several nodes. I have a HAProxy running as a service in Swarm.
I want to setup LetsEncrypt on one of the hosts node. But for that I need HAProxy to redirect the authorization requests to the certbot which runs in standalone mode on one of the hosts node.
Any Idea how can I do it ?

**Comment by qoomon** [comment]
Did you tried it already? I'm not used to docker swarm, however it should still work? 
If its not working out of the box you may can provide the host ip manually by passing `DOCKER_HOST ` environment variable to docker-host container.

**Comment by xirius** [comment]
Actually it worked, awesome. I had an issue with HAProxy config. You can close it. Thanks.
