### ISSUE TITLE
Build for ARM

### ISSUE THREAD

**Issue by pathob** [qoomon/docker-host#35]
Hi, it would be very nice if you could also build your image for ARM. Thank you!

**Comment by qoomon** [comment]
How to?

**Comment by qoomon** [comment]
like this https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/?

**Comment by pathob** [comment]
I guess yes. The other approach might be to use an ARM container in travis for building, but I don't know how the tagging is done then in order to get a result like this: https://hub.docker.com/_/alpine?tab=tags

Unfortunately, I don't have experience with deploying Docker images or building for other architectures.

My current solution is to just build your image directly on ARM and that works fine. So at least I can confirm there are no architecture-specific changes necessary.

**Comment by sdemets** [comment]
There are plenty of how-to's out there on building cross platform images, but here's how I do it to build python based images (FROM python) for my PC and Raspberry Pi in one go on my Windows 10 machine:

use docker buildx (experimental CLI)
docker buildx create --name rpibuilder
docker buildx use rpibuilder
docker buildx inspect --bootstrap
docker buildx build --platform linux/amd64,linux/arm/v7 -t <imagename>:<tag> <path to dockerfile> --push
docker buildx imagetools inspect <imagename>:<tag>

The last line is just to check if all went well.

Hope this helps!

**Comment by qoomon** [comment]
Oh nice. Will try to add it to github action deploy pipeline.

**Comment by qoomon** [comment]
enable experimental features is easy as `export DOCKER_CLI_EXPERIMENTAL=enabled` :-D

**Comment by sdemets** [comment]
If you have Docker Desktop, just go to settings -> command line and set "Enable experimental features" to on.

**Comment by qoomon** [comment]
just released `qoomon/docker-host:latest` and `qoomon/docker-host:2.4.2` to dockerhub for following platforms
* linux/amd64
* linux/arm/v7
* linux/arm64
