### ISSUE TITLE
allow access to other resources on host network?

### ISSUE THREAD

**Issue by allandaly** [qoomon/docker-host#39]
I did not know the best way to contact you so I hope that creating an 'issue' here is OK.

I just posted [this StackOverflow question](https://stackoverflow.com/questions/63874681/connect-from-inside-a-docker-container-to-ip-address-on-host-network) and I wondered if docker-host might be a solution to my situation. Could I please ask you to take a look?

Thank you.
-Allan

**Comment by qoomon** [comment]
Hi, it's a strange behaviour cause it should work out of the box. What you can try is to create `docker-host`container with environment variable `DOCKER_HOST ` and set it to your destination ip, see example below. And then you should be able to connect to `docker-host` as your target host like `curl docker-host`
```shell
    docker-host:
            image: qoomon/docker-host
            cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
            mem_limit: 8M
            environment:
                - DOCKER_HOST=192.168.1.50
            restart: on-failure
```

**Comment by qoomon** [comment]
maybe the strange behaviour is related to docker network range overlapping, see https://stackoverflow.com/a/42492941/5376635

**Comment by qoomon** [comment]
this might be the root cause https://github.com/moby/moby/issues/37823#issuecomment-421186655

**Comment by qoomon** [comment]
glad to hear you solved it -> https://stackoverflow.com/a/63879038/5376635
