### ISSUE TITLE
Can't get it to work with `sam local`

### ISSUE THREAD

**Issue by ben8p** [qoomon/docker-host#41]
I am trying to setup communication from a docker container to a port on the host.  
The port is managed by `sam local` (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-start-lambda.html)

`sam local` listen on port 3001 by default.  
For the sake of testing, I also run `nc -p 2323 -lk` in a separate terminal.

- hitting `http://localhost:2323/` from a browser show information in the `nc` terminal
- hitting `http://localhost:3001/` from a browser show information in the `sam local` terminal

running 
```
docker run --rm \
  --link 'docker-host' \
  -it alpine nc 'docker-host' 2323 -v
```
allow me to communicate with the host, so it seems `docker-host` is correctly setup.

however...
running 
```
docker run --rm \
  --link 'docker-host' \
  -it alpine nc 'docker-host' 3001 -v
```
simply returns... without any message... 
like if the port was not open... 
and of course the exit code is `1` so not very useful...

This drives me nuts... so any help would be greatly appreciated...

I am running it on Ubuntu    
and the firewall is configured to let everything pass: `sudo ufw allow from xx.xx.xx.xx`

Also, when running `nc localhost 3002 -v` on host machine (where `sam local` is started) it works:  
`Connection to localhost 3002 port [tcp/*] succeeded!`

**Comment by ben8p** [comment]
Well, my issue is probably unrelated to this image...
Using `alpine-ssh`, I ran the following command (20.20.0.1 is the IP of the host machine)
`telnet 20.20.0.1 2323`
the connection is successful

`telnet 20.20.0.1 3002`
> telnet: can't connect to remote host (20.20.0.1): Connection refused

That still makes no sense to me...

**Comment by ben8p** [comment]
Ok, found the issue... `sam local` needs to be bound to `0.0.0.0` using `sam local start-lambda --host 0.0.0.0`

**Comment by qoomon** [comment]
glad to hear your solved it already.
