### ISSUE TITLE
Docker-host container takes ~10 seconds to shut down in docker compose

### ISSUE THREAD

**Issue by a3957273** [qoomon/docker-host#45]
Running: Docker for Mac
Version: Docker version 20.10.12, build e91ed57

We have a compose file with half a dozen dependencies which take between 0.2 and 0.4 seconds to shut down on average.  The `docker-host` container takes 10.2 seconds to shut down, significantly outweighing all other containers.  Is there a reason for this lengthy shut down time?

It seems to _reliably_ take 10.2 - 10.3 seconds to shut down.  Almost as if it's taking the 'normal shut down time' and adding precisely 10 seconds somewhere.

**Comment by qoomon** [comment]
I think it is because auf the default `docker-compose down` timeout see https://docs.docker.com/compose/reference/down/

However I'll investigate why docker-host container runs into timeout.

**Comment by qoomon** [comment]
should be fixed in version `3.0.5`

**Comment by qoomon** [comment]
@a3957273  Could you confirm the fix is working?
