### ISSUE TITLE
CHAIN_ADD failed (No such file or directory): chain PREROUTING

### ISSUE THREAD

**Issue by xehonk** [qoomon/docker-host#62]
In the new release (3.1.4) there is an error, which prevents the container from starting. Only happened on a windows host, not on a linux host.
iptables v1.8.10 (nf_tables): CHAIN_ADD failed (No such file or directory): chain PREROUTING

![image (21)](https://github.com/qoomon/docker-host/assets/4105324/056d2d63-5734-4c8e-a903-d33817b8fea2)

**Comment by qoomon** [comment]
Hmm, do you have any idea why this happens?(I don't have a windows machine)

**Comment by qoomon** [comment]
@xehonk do you use docker with wsl2 enabled? https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers

**Comment by xehonk** [comment]
@qoomon Sorry, I don't have access to the affected machine until next week. I'll find out then.

**Comment by xehonk** [comment]
So, here's the update:
The machine has wsl2 enabled. docker-desktop and docker-desktop-data images are installed.

```
$ docker run --cap-add=NET_ADMIN --cap-add=NET_RAW qoomon/docker-host:3.1.5
Docker Host: 192.168.65.2 (host.docker.internal)
Forwarding ports: 1-65535
Warning: Extension tcp revision 0 not supported, missing kernel module?
Warning: Extension DNAT revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING

$ docker run --cap-add=NET_ADMIN --cap-add=NET_RAW qoomon/docker-host:3.1.4
Docker Host: 192.168.65.2 (host.docker.internal)
Forwarding ports: 1-65535
Warning: Extension tcp revision 0 not supported, missing kernel module?
Warning: Extension DNAT revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING

$ docker run --cap-add=NET_ADMIN --cap-add=NET_RAW qoomon/docker-host:3.1.3
Docker Host: 192.168.65.2 (host.docker.internal)
Forwarding ports: 1-65535
```

**Comment by qoomon** [comment]
probably it's due to iptables-nft change in alpine version 3.19.0 https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.19.0

**Comment by qoomon** [comment]
Maybe adding following lines to entrypoint.sh before iptable commands could help
```shell
modprobe ip_tables && echo $_ >> /etc/modules
modprobe iptable_nat && echo $_ >> /etc/modules
modprobe iptable_filter && echo $_ >> /etc/modules
```

**Comment by qoomon** [comment]
feel free to try this branch https://github.com/qoomon/docker-host/tree/feature/migrate-to-nftables

**Comment by xehonk** [comment]
Works on my linux machine, but same error on windows unfortunately:
![image (22)](https://github.com/user-attachments/assets/277d9177-89aa-4bc0-85b2-bded73feaec0)

**Comment by qoomon** [comment]
hmm i have no clue what the reason, or why the iptables legacy solution works

**Comment by qoomon** [comment]
seems to be related to https://github.com/rancher-sandbox/rancher-desktop/issues/6624

**Comment by qoomon** [comment]
I switched to iptables-legacy. Feel free to try version 3.3.0

**Comment by xehonk** [comment]
I can confirm that it works with 3.3 on windows and linux. here the run from the previously broken windows pc:

![image (24)](https://github.com/user-attachments/assets/3e615b35-2474-4cb9-824b-98dc9d7d5707)
