### ISSUE TITLE
connecting to database on host

### ISSUE THREAD

**Issue by xandriaw** [qoomon/docker-host#7]
Should this work for connecting to a database on the host?
I have a mysql db on my host. When i run your container I am able to ping the "dockerhost" from my other containers. But when I go to connect to the database, I get an error. I'm using R, so it's fine if you're not familiar with the program.

command line:
```
root@3fb860760a17:/# ping dockerhost
PING dockerhost (172.18.0.3): 56 data bytes
64 bytes from 172.18.0.3: icmp_seq=0 ttl=64 time=0.178 ms
```
in R:
```
> DB<-dbConnect(MySQL(), user = 'buko-user', password ='buko-access',
+                 dbname = 'buko', host = '172.18.0.3')
Error in .local(drv, ...) : 
  Failed to connect to database: Error: Can't connect to MySQL server on '172.18.0.3' (107)
```

**Comment by qoomon** [comment]
i will investigate

**Comment by qoomon** [comment]
I tested it on my machine with following commands. Can you run them on your machine and tell me if it worked?

Run those in different shells.
```shell
# start mysql server bin port to local host
docker run -it --rm \
-p 3306:3306 -e MYSQL_ROOT_PASSWORD=root \
mysql

# start docker-host
docker run -it --rm --name 'dockerhost' \
--cap-add=NET_ADMIN --cap-add=NET_RAW \
qoomon/docker-host

# mysql client connect to mysql server through 'dockerhost' container
docker run -it --rm  --link 'dockerhost' \
mysql mysql -h'dockerhost' -u'root' -p'root'
```

**Comment by qoomon** [comment]
Which host OS you use?

**Comment by qoomon** [comment]
any news?

**Comment by xandriaw** [comment]
Sorry for the delay on this! We decided to move the database to a different
server and we don't have to deal with this problem anymore.

**Comment by qoomon** [comment]
Could you test it anyway?

**Comment by xandriaw** [comment]
Next week I may have time to test. I'm a consultant so I'm not paid for
extra work. 😒

**Comment by qoomon** [comment]
Thx that would be great.
